### ISSUE TITLE
hard coded database name

### ISSUE THREAD

**Issue by aroute** [evilADevil/mas-techzone#1]
https://github.com/evilADevil/mas-techzone/blob/59ebc3dbcca655308e0a03bd843494f5a7803cf6/masocpl.yml#L25

FYI. This is due to the fact that `bludb` is hardcoded [here](https://github.com/ibm-mas/ansible-devops/blob/fa2443f7136a68169d7910fcd9b67abb603adf62/ibm/mas_devops/roles/db2/tasks/create_ldap_user.yml#L53) on line number 53.

I have in the past created an Issue at masdevops for the resolution [#460](https://github.com/ibm-mas/ansible-devops/issues/460).

**Comment by evilADevil** [comment]
Yep, I was aware and reported this issue also. Thx
